on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: List Files
        run: ls -lrt

      - name: Print Working Directory
        run: pwd
